#!/usr/bin/env python3
"""score_task.py -- automated scorer for the DSV4 vs Qwen3.8 A/B (see ab/SCORING.md).

usage:
  python score_task.py <task> <label>     score one run, write _runs/<task>/<label>/score.json
  python score_task.py --all              score every run dir present, also write _runs/scoreboard.md

<task> in {radix, anyio, hatetris, chessground, chessground-322, chessjs}
<label> matches the worktree/run-dir naming from run_omp_task.sh (e.g. "dsv4", "qwen", "qwen-med").

Layout assumed (see run_omp_task.sh):
  D:/dev/ab-tasks/_briefs/<task>/turns.json   -- {"repo"/"dir", "test_cmd", "install", "turns":[...]}
  D:/dev/ab-tasks/_hidden/<task>/fix-pr-*.diff, issue-*.json, repro-*.test.ts
  D:/dev/ab-tasks/<task>-<label>/             -- model's worktree (final state, uncommitted diff on disk)
  D:/dev/ab-tasks/_runs/<task>/<label>/       -- final.diff, turn-*.json, driver.log, sessions/, final-tests.log,
                                                  base-sha.txt

P1/P2/P3 are defined in ab/SCORING.md section 2A/2B. This script is deliberately conservative about mutating
anything outside of a run's own scratch scaffolding: the model's worktree is only ever touched via an
apply-run-restore cycle (P1) that puts back exactly what was there before, and P3's "does the model's own test
fail on the base commit" check happens in a disposable `git worktree` next to the base clone, never in the base
clone itself.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path("D:/dev/ab-tasks")
RUNS = ROOT / "_runs"
BRIEFS = ROOT / "_briefs"
HIDDEN = ROOT / "_hidden"

TASKS = ["radix", "anyio", "hatetris", "chessground", "chessground-322", "chessjs"]

# final.diff / upstream diffs both come from `git diff`; these are lockfile/build noise excluded from
# final.diff by run_omp_task.sh itself (':!package-lock.json' ':!pnpm-lock.yaml') -- apply the same exclusion
# to upstream diffs so LOC/precision comparisons are apples-to-apples.
EXCLUDE_BASENAMES = {"package-lock.json", "pnpm-lock.yaml", "yarn.lock"}

TEST_PATH_RE = re.compile(r"(?i)(^|[\\/])(__tests__|tests?|spec)([\\/]|$)|\.(test|spec)\.")

RUN_TOOL_NAMES = {"bash", "eval", "command", "shell", "exec", "execute", "run", "terminal", "cmd"}

# gitignored files that are generated by a task's install/build step and are required just to
# import the source under test, so a bare `git worktree add` (used for P3's scratch worktree,
# which never runs install) won't have them. Copied in (not junctioned -- small, generated,
# deterministic from tracked sources) alongside the node_modules/.venv junction. Discovered via
# chessjs: src/pgn.js + src/pgn.d.ts come from the peggy parser build step (`npm run parser`,
# part of `prepare`/`build`), are in .gitignore, and chess.ts fails to import without them.
EXTRA_GENERATED_FILES = {
    "chessjs": ["src/pgn.js", "src/pgn.d.ts"],
}

# live-bug tasks (SCORING.md 2B): P1 is a frozen, pre-written repro test from _hidden/, not an
# upstream fix diff. hidden_dir is where the frozen test file actually lives under _hidden/ --
# NOT necessarily the task name: chessground-322 reuses the chessground #386 task's worktree
# lineage (base repo D:/dev/ab-tasks/chessground, distinct from chessground-ref which the
# existing "chessground"/#386 task uses) but its hidden material sits under _hidden/chessground/
# alongside #386's, keyed by issue number in the filename.
FROZEN_REPRO = {
    "chessground": {"hidden_dir": "chessground", "file": "repro-386.test.ts", "dest_dir": "tests"},
    "chessground-322": {"hidden_dir": "chessground", "file": "repro-322.test.ts", "dest_dir": "tests"},
    "chessjs": {"hidden_dir": "chessjs", "file": "repro-577.test.ts", "dest_dir": "__tests__"},
}

HARNESS_ERR_RE = re.compile(
    r"(?i)(validation failed for tool|invalid json|failed to pars|malformed|unexpected token"
    r"|parse error|schema mismatch|unknown tool|no such tool)"
)
FAIL_TEXT_RE = re.compile(r"(?i)\b(fail(?:ed|ure)?|error|exception|traceback|assertionerror)\b")


# --------------------------------------------------------------------------------------
# small utilities
# --------------------------------------------------------------------------------------

def tail(s, n=4000):
    if s is None:
        return None
    return s[-n:]


def load_turns(task: str) -> dict:
    p = BRIEFS / task / "turns.json"
    return json.loads(p.read_text(encoding="utf-8"))


def base_repo_dir(turns: dict) -> Path:
    return Path(turns["repo"])


def worktree_dir(task: str, label: str) -> Path:
    return ROOT / f"{task}-{label}"


def run_out_dir(task: str, label: str) -> Path:
    return RUNS / task / label


def assert_within(path: Path, root: Path):
    rp = path.resolve()
    rr = root.resolve()
    if rr != rp and rr not in rp.parents:
        raise RuntimeError(f"refusing to operate outside {root}: {path}")


def winize_leading_path(cmd: str) -> str:
    """cmd.exe (our shell=True) cannot launch a relative executable whose path uses forward
    slashes -- e.g. `.venv/Scripts/python -m pytest ...` fails with "'.' is not recognized",
    even though the identical string works fine as a bash command (anyio's turns.json test_cmd
    is written exactly that way). Only the *leading executable token* needs backslashes:
    arguments after it are parsed by that program (python/pytest/etc.), not by cmd.exe, so
    forward slashes there are unaffected and left alone. Bare command names like `npx`/`pnpm`/
    `node` (no '/', no leading '.') are untouched -- cmd.exe resolves those via PATH either way.
    """
    m = re.match(r"^(\S+)(.*)$", cmd, re.S)
    if not m:
        return cmd
    head, rest = m.group(1), m.group(2)
    if "/" in head and (head.startswith(".") or head.startswith("/") or re.match(r"^[A-Za-z]:", head)):
        head = head.replace("/", "\\")
    return head + rest


def run_shell(cmd: str, cwd: Path, timeout: int):
    """Run `cmd` via cmd.exe (shell=True), inheriting this process's own PATH/env.

    Deliberately NOT `bash -lc`: spawning a fresh git-bash login shell from a native python.exe
    process was observed to source a different PATH than the one this script is actually running
    under, and could resolve `node`/`npx` to a broken WSL shim ("WSL 1 is not supported...") even
    though the same command works fine when run directly in the interactive shell. shell=True
    inherits this process's real, working environment instead.
    """
    cmd = winize_leading_path(cmd)
    try:
        r = subprocess.run(
            cmd, cwd=str(cwd), stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            text=True, encoding="utf-8", errors="replace", timeout=timeout, shell=True,
        )
        return r.returncode, r.stdout
    except subprocess.TimeoutExpired as e:
        out = e.stdout or ""
        if isinstance(out, bytes):
            out = out.decode("utf-8", "replace")
        return -1, out + f"\n[TIMEOUT after {timeout}s]"


def quote(f: str) -> str:
    return '"' + f.replace("\\", "/") + '"'


def is_test_path(path: str) -> bool:
    return bool(TEST_PATH_RE.search(path.replace("\\", "/")))


# --------------------------------------------------------------------------------------
# unified-diff parsing (used for both final.diff and the upstream fix-pr-*.diff)
# --------------------------------------------------------------------------------------

def split_diff_blocks(text: str) -> list[dict]:
    """Split a `git diff` text into per-file blocks: [{'path','text','is_new','is_del'}]."""
    blocks: list[dict] = []
    cur = None
    for line in text.splitlines(keepends=True):
        m = re.match(r"^diff --git a/(.*?) b/(.*?)[\r\n]*$", line)
        if m:
            if cur:
                blocks.append(cur)
            cur = {"path": m.group(2).strip(), "text": line, "is_new": False, "is_del": False}
            continue
        if cur is None:
            continue
        cur["text"] += line
        if line.startswith("new file mode"):
            cur["is_new"] = True
        if line.startswith("deleted file mode"):
            cur["is_del"] = True
    if cur:
        blocks.append(cur)
    return blocks


def parse_diff(text: str) -> list[dict]:
    """Per-file summary: path, additions, deletions, new_file, deleted_file, binary."""
    out = []
    for b in split_diff_blocks(text):
        additions = deletions = 0
        binary = False
        for line in b["text"].splitlines():
            if line.startswith("Binary files"):
                binary = True
            elif line.startswith("+++") or line.startswith("---"):
                continue
            elif line.startswith("+"):
                additions += 1
            elif line.startswith("-"):
                deletions += 1
        out.append({
            "path": b["path"], "additions": additions, "deletions": deletions,
            "new_file": b["is_new"], "deleted_file": b["is_del"], "binary": binary,
        })
    return out


def filtered(files: list[dict]) -> list[dict]:
    return [f for f in files if Path(f["path"]).name not in EXCLUDE_BASENAMES]


def extract_new_file_content(block_text: str) -> str:
    """For a `new file mode` diff block, reconstruct the added file's full content."""
    out = []
    in_hunk = False
    for line in block_text.splitlines():
        if line.startswith("@@"):
            in_hunk = True
            continue
        if not in_hunk:
            continue
        if line.startswith("+"):
            out.append(line[1:])
        elif line.startswith("\\ No newline"):
            continue
    return ("\n".join(out) + "\n") if out else ""


def reconstruct_via_patch(pristine_path: Path, diff_block_text: str) -> str | None:
    """Apply a single-file diff hunk to pristine_path's content using GNU patch, return the result."""
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        work = td / pristine_path.name
        work.write_bytes(pristine_path.read_bytes())
        patchfile = td / "x.patch"
        patchfile.write_text(diff_block_text, encoding="utf-8")
        outfile = td / "out.txt"
        r = subprocess.run(
            f'patch -o "{outfile.as_posix()}" "{work.as_posix()}" < "{patchfile.as_posix()}"',
            cwd=str(td), capture_output=True, text=True, encoding="utf-8", errors="replace", shell=True,
        )
        if r.returncode != 0 or not outfile.exists():
            return None
        return outfile.read_text(encoding="utf-8", errors="replace")


# --------------------------------------------------------------------------------------
# per-task "run just these test file(s)" command builders
# --------------------------------------------------------------------------------------

def strip_coverage_flags(script: str) -> list[str]:
    tokens = re.findall(r'"[^"]*"|\S+', script)
    out = []
    i = 0
    while i < len(tokens):
        t = tokens[i]
        if t == "--experimental-test-coverage":
            i += 1
            continue
        if t.startswith("--test-coverage-") and "=" in t:
            i += 1
            continue
        if t == "--test-coverage-exclude":
            i += 2  # flag + its quoted value
            continue
        out.append(t)
        i += 1
    return out


def build_single_test_cmd(task: str, cwd: Path, files: list[str]) -> str:
    files = [f.replace("\\", "/") for f in files]
    if task in ("radix", "chessground", "chessground-322", "chessjs"):
        return "npx --no-install vitest run " + " ".join(quote(f) for f in files)
    if task == "anyio":
        return "./.venv/Scripts/python -m pytest " + " ".join(quote(f) for f in files) + " -q"
    if task == "hatetris":
        pkg_path = cwd / "package.json"
        unit = ""
        if pkg_path.exists():
            try:
                unit = json.loads(pkg_path.read_text(encoding="utf-8")).get("scripts", {}).get("unit", "")
            except Exception:
                unit = ""
        if not unit:
            # observed default, kept as a fallback if package.json is unreadable
            unit = (
                'node --enable-source-maps --import ./register.js --require global-jsdom/register '
                '--test -- "**/*.test.{ts,tsx}"'
            )
        toks = strip_coverage_flags(unit)
        if len(toks) >= 2 and toks[-2] == "--":
            toks = toks[:-1] + [quote(f) for f in files]
        else:
            toks = toks + ["--"] + [quote(f) for f in files]
        return " ".join(toks)
    raise ValueError(f"unknown task {task}")


def nearest_pkg_root(base_repo: Path, rel_test_path: str) -> Path:
    """Walk up from a test file toward base_repo, return the nearest dir with package.json/pyproject.toml."""
    p = Path(rel_test_path).parent
    while True:
        if (base_repo / p / "package.json").exists() or (base_repo / p / "pyproject.toml").exists():
            return p
        if str(p) in (".", ""):
            return Path(".")
        parent = p.parent
        if parent == p:
            return Path(".")
        p = parent


# --------------------------------------------------------------------------------------
# git / worktree / junction helpers
# --------------------------------------------------------------------------------------

def git(args: list[str], cwd: Path):
    return subprocess.run(["git"] + args, cwd=str(cwd), capture_output=True, text=True, encoding="utf-8", errors="replace")


def get_base_sha(run_out: Path, base_repo: Path) -> str:
    f = run_out / "base-sha.txt"
    if f.exists():
        s = f.read_text(encoding="utf-8").strip()
        if s:
            return s
    return git(["rev-parse", "HEAD"], base_repo).stdout.strip()


def make_scratch_worktree(base_repo: Path, path: Path, sha: str):
    if path.exists():
        raise RuntimeError(f"scratch worktree path already exists, refusing to reuse: {path}")
    r = git(["worktree", "add", "-q", "--detach", str(path), sha], base_repo)
    if r.returncode != 0:
        raise RuntimeError(f"git worktree add failed for {path}: {r.stderr.strip()}")


def remove_scratch_worktree(base_repo: Path, path: Path):
    assert "-p3scratch-" in path.name, f"refusing non-scratch worktree removal: {path}"
    if not path.exists():
        git(["worktree", "prune"], base_repo)
        return
    r = git(["worktree", "remove", "--force", str(path)], base_repo)
    if r.returncode != 0:
        git(["worktree", "prune"], base_repo)
        # last resort -- safe here because make_junction/remove_junction already stripped every
        # reparse point we created, so nothing left under `path` can be a junction back into the
        # base repo's real node_modules/.venv.
        try:
            shutil.rmtree(path, ignore_errors=True)
        except Exception:
            pass
        git(["worktree", "prune"], base_repo)


def make_junction(link: Path, target: Path):
    link.parent.mkdir(parents=True, exist_ok=True)
    if link.exists():
        return
    r = subprocess.run(["cmd", "/c", "mklink", "/J", str(link), str(target)], capture_output=True, text=True, encoding="utf-8", errors="replace")
    if r.returncode != 0:
        raise RuntimeError(f"junction failed ({link} -> {target}): {r.stdout} {r.stderr}")


def remove_junction(link: Path):
    """Non-recursive rmdir: removes the reparse point only, never the junction's target contents."""
    if not link.exists():
        return
    r = subprocess.run(["cmd", "/c", "rmdir", str(link)], capture_output=True, text=True, encoding="utf-8", errors="replace")
    if r.returncode != 0:
        print(f"WARNING: failed to remove junction {link}: {r.stdout} {r.stderr}", file=sys.stderr)


# --------------------------------------------------------------------------------------
# P1 -- upstream/frozen test passes on the model's worktree
# --------------------------------------------------------------------------------------

def p1_upstream_test_blocks(task: str) -> list[dict]:
    diffs = sorted(HIDDEN.glob(f"{task}/fix-pr-*.diff"))
    if not diffs:
        return []
    text = diffs[0].read_text(encoding="utf-8", errors="replace")
    return [b for b in split_diff_blocks(text) if is_test_path(b["path"])]


def apply_p1_diff_file(wt: Path, base_repo: Path, block: dict, run_out: Path) -> dict:
    """Write/patch one upstream test file into the model's worktree.
    Returns {'run_path','created':[Path,...],'restore':[(Path,bytes),...],'conflict':bool}.
    """
    rel = block["path"]
    target = wt / rel
    created: list[Path] = []
    restore: list[tuple[Path, bytes]] = []
    conflict = False

    if block["is_new"]:
        content = extract_new_file_content(block["text"])
        if target.exists():
            conflict = True
            dest = target.parent / f"zz-upstream-{target.name}"
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")
            created.append(dest)
            run_path = dest.relative_to(wt).as_posix()
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            created.append(target)
            run_path = rel
        return {"run_path": run_path, "created": created, "restore": restore, "conflict": conflict}

    # modification of an existing file: try a scoped git apply directly in the worktree first.
    original = target.read_bytes() if target.exists() else None
    patch_file = run_out / f".p1-{Path(rel).name}.patch"
    patch_file.write_text(block["text"], encoding="utf-8")
    r = subprocess.run(
        ["git", "apply", f"--include={rel}", "--whitespace=nowarn", str(patch_file)],
        cwd=str(wt), capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    patch_file.unlink(missing_ok=True)
    if r.returncode == 0:
        if original is not None:
            restore.append((target, original))
        else:
            created.append(target)
        return {"run_path": rel, "created": created, "restore": restore, "conflict": False}

    # conflict: reconstruct the upstream version against the PRISTINE base-repo copy of the file
    # (never against the model's edited copy) and drop it in as a zz-upstream sibling.
    conflict = True
    pristine = base_repo / rel
    if not pristine.exists():
        raise RuntimeError(f"P1 conflict on {rel} and no pristine base copy to reconstruct from")
    reconstructed = reconstruct_via_patch(pristine, block["text"])
    if reconstructed is None:
        raise RuntimeError(f"P1 conflict on {rel}: git apply failed ({r.stderr.strip()[:200]}) and "
                            f"fallback `patch` reconstruction also failed")
    dest = target.parent / f"zz-upstream-{target.name}"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(reconstructed, encoding="utf-8")
    created.append(dest)
    return {"run_path": dest.relative_to(wt).as_posix(), "created": created, "restore": restore, "conflict": conflict}


def cleanup_p1(applied: dict):
    for p in applied.get("created", []):
        try:
            Path(p).unlink()
        except FileNotFoundError:
            pass
    for p, content in applied.get("restore", []):
        Path(p).write_bytes(content)


def run_p1(task: str, wt: Path, base_repo: Path, run_out: Path, timeout: int) -> dict:
    if task in FROZEN_REPRO:
        spec = FROZEN_REPRO[task]
        frozen = HIDDEN / spec["hidden_dir"] / spec["file"]
        dest_dir = wt / spec["dest_dir"]
        if not frozen.exists():
            return {"status": "ERROR", "reason": f"frozen repro test missing: {frozen}"}
        dest = dest_dir / frozen.name
        conflict = dest.exists()
        if conflict:
            dest = dest_dir / f"zz-upstream-{frozen.name}"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(frozen.read_text(encoding="utf-8"), encoding="utf-8")
        run_path = dest.relative_to(wt).as_posix()
        cmd = build_single_test_cmd(task, wt, [run_path])
        try:
            rc, log = run_shell(cmd, wt, timeout)
        finally:
            try:
                dest.unlink()
            except FileNotFoundError:
                pass
        return {"status": "PASS" if rc == 0 else "FAIL", "files": [run_path], "rc": rc, "cmd": cmd,
                "conflict": conflict, "log_tail": tail(log)}

    blocks = p1_upstream_test_blocks(task)
    if not blocks:
        return {"status": "ERROR", "reason": "no test files found in upstream fix-pr diff", "files": []}

    applied_list = []
    run_paths = []
    rc, log, cmd = None, None, None
    try:
        for b in blocks:
            a = apply_p1_diff_file(wt, base_repo, b, run_out)
            applied_list.append(a)
            run_paths.append(a["run_path"])
        cmd = build_single_test_cmd(task, wt, run_paths)
        rc, log = run_shell(cmd, wt, timeout)
    except Exception as e:
        return {"status": "ERROR", "reason": str(e), "files": run_paths}
    finally:
        for a in applied_list:
            cleanup_p1(a)

    return {
        "status": "PASS" if rc == 0 else "FAIL", "files": run_paths, "rc": rc, "cmd": cmd,
        "conflicts": [a["run_path"] for a in applied_list if a.get("conflict")],
        "log_tail": tail(log),
    }


# --------------------------------------------------------------------------------------
# P2 -- full pre-registered suite is green
# --------------------------------------------------------------------------------------

def run_p2(wt: Path, turns: dict, timeout: int) -> dict:
    cmd = turns["test_cmd"]
    rc, log = run_shell(cmd, wt, timeout)
    return {"status": "PASS" if rc == 0 else "FAIL", "rc": rc, "cmd": cmd, "log_tail": tail(log)}


# --------------------------------------------------------------------------------------
# P3 -- test honesty: model's own test passes on its worktree, fails on the base commit
# --------------------------------------------------------------------------------------

def run_p3(task: str, wt: Path, base_repo: Path, run_out: Path, label: str, timeout: int) -> dict:
    diff_path = run_out / "final.diff"
    if not diff_path.exists():
        return {"status": "ERROR", "reason": "final.diff missing"}
    diff_text = diff_path.read_text(encoding="utf-8", errors="replace")
    files = parse_diff(diff_text)
    model_test_files = [
        f["path"] for f in files
        if is_test_path(f["path"]) and not f["deleted_file"] and not f["binary"]
        and Path(f["path"]).name not in EXCLUDE_BASENAMES
    ]
    if not model_test_files:
        return {"status": "FAIL", "reason": "model added/changed no test file (honesty check requires one)",
                "files": []}

    cmd = build_single_test_cmd(task, wt, model_test_files)
    rc_a, log_a = run_shell(cmd, wt, timeout)
    passed_a = (rc_a == 0)

    result = {
        "files": model_test_files, "cmd": cmd,
        "model_worktree_pass": passed_a, "model_log_tail": tail(log_a),
    }

    base_sha = get_base_sha(run_out, base_repo)
    scratch = ROOT / f"{task}-p3scratch-{label}"
    assert_within(scratch, ROOT)
    junctions: list[Path] = []
    try:
        make_scratch_worktree(base_repo, scratch, base_sha)
        dep_dirs = {Path(".")}
        for tf in model_test_files:
            dep_dirs.add(nearest_pkg_root(base_repo, tf))
        for d in dep_dirs:
            src_nm = base_repo / d / "node_modules"
            if src_nm.exists():
                link = scratch / d / "node_modules"
                make_junction(link, src_nm)
                junctions.append(link)
            src_venv = base_repo / d / ".venv"
            if src_venv.exists():
                link = scratch / d / ".venv"
                make_junction(link, src_venv)
                junctions.append(link)

        for extra in EXTRA_GENERATED_FILES.get(task, []):
            src = base_repo / extra
            if src.exists():
                dst = scratch / extra
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)

        warnings = []
        for tf in model_test_files:
            src = wt / tf
            dst = scratch / tf
            if src.exists():
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)
            else:
                warnings.append(f"model test file missing in worktree: {tf}")
        if warnings:
            result["warnings"] = warnings

        rc_b, log_b = run_shell(cmd, scratch, timeout)
        base_fails = (rc_b != 0)
        result["base_worktree_fail_as_expected"] = base_fails
        result["base_sha"] = base_sha
        result["base_log_tail"] = tail(log_b)

        if not passed_a:
            result["status"] = "FAIL"
            result["reason"] = "model's own test does not pass in the model's worktree"
        elif not base_fails:
            result["status"] = "FAIL"
            result["reason"] = ("model's own test also passes on the base commit -- it does not "
                                 "demonstrate the bug/fix (honesty check failed)")
        else:
            result["status"] = "PASS"
    except Exception as e:
        result["status"] = "ERROR"
        result["reason"] = str(e)
    finally:
        for j in reversed(junctions):
            remove_junction(j)
        try:
            remove_scratch_worktree(base_repo, scratch)
        except Exception as e:
            result.setdefault("warnings", []).append(f"scratch cleanup issue: {e}")

    return result


# --------------------------------------------------------------------------------------
# secondary: diff size / precision vs upstream
# --------------------------------------------------------------------------------------

def secondary_metrics(task: str, run_out: Path) -> dict:
    diff_path = run_out / "final.diff"
    diff_text = diff_path.read_text(encoding="utf-8", errors="replace") if diff_path.exists() else ""
    files = filtered(parse_diff(diff_text))
    loc_added = sum(f["additions"] for f in files)
    loc_removed = sum(f["deletions"] for f in files)
    touched = [f["path"] for f in files]
    non_test_touched = [f["path"] for f in files if not is_test_path(f["path"])]

    upstream_diffs = sorted(HIDDEN.glob(f"{task}/fix-pr-*.diff"))
    precision = None
    upstream_non_test = None
    if upstream_diffs:
        u_files = filtered(parse_diff(upstream_diffs[0].read_text(encoding="utf-8", errors="replace")))
        upstream_non_test = [f["path"] for f in u_files if not is_test_path(f["path"])]
        precision = all(p in set(upstream_non_test) for p in non_test_touched) if non_test_touched else None

    return {
        "loc_added": loc_added, "loc_removed": loc_removed,
        "files_touched": touched, "files_touched_count": len(touched),
        "non_test_files_touched": non_test_touched,
        "upstream_non_test_files": upstream_non_test,
        "precision_subset_of_upstream": precision,
    }


# --------------------------------------------------------------------------------------
# OMP event-stream analysis (turn-*.json preferred, sessions/*.jsonl fallback)
# schema learned by inspecting real session store jsonl under ~/.omp/agent/sessions (read-only);
# exact turn-*.json shape from `--mode json` is not directly observed, so this stays defensive:
# any field it cannot find comes back null/None rather than raising.
# --------------------------------------------------------------------------------------

def load_ndjson_or_json(path: Path):
    events, parse_errors = [], 0
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return events, parse_errors
    lines = [l for l in text.splitlines() if l.strip()]
    ok_any = False
    for l in lines:
        try:
            d = json.loads(l)
        except json.JSONDecodeError:
            parse_errors += 1
            continue
        if isinstance(d, dict):
            events.append(d)
            ok_any = True
        elif isinstance(d, list):
            events.extend(x for x in d if isinstance(x, dict))
            ok_any = True
    if not ok_any and text.strip():
        try:
            d = json.loads(text)
            if isinstance(d, list):
                events = [x for x in d if isinstance(x, dict)]
            elif isinstance(d, dict):
                for key in ("events", "messages", "items", "log"):
                    if isinstance(d.get(key), list):
                        events = [x for x in d[key] if isinstance(x, dict)]
                        break
                else:
                    events = [d]
            parse_errors = 0
        except Exception:
            pass
    return events, parse_errors


def walk_dicts(obj, depth=0, maxdepth=14):
    if depth > maxdepth:
        return
    if isinstance(obj, dict):
        yield obj
        for v in obj.values():
            yield from walk_dicts(v, depth + 1, maxdepth)
    elif isinstance(obj, list):
        for v in obj:
            yield from walk_dicts(v, depth + 1, maxdepth)


def is_failure_result(res: dict | None) -> bool | None:
    if res is None:
        return None
    if res.get("isError"):
        return True
    d = res.get("details") or {}
    cells = d.get("cells")
    if isinstance(cells, list):
        for c in cells:
            ec = c.get("exitCode") if isinstance(c, dict) else None
            if isinstance(ec, int) and ec != 0:
                return True
    ec = d.get("exitCode")
    if isinstance(ec, int) and ec != 0:
        return True
    if FAIL_TEXT_RE.search(res.get("text", "") or ""):
        return True
    return False


def analyze_events(run_out: Path, test_cmd: str) -> dict:
    turn_files = sorted(
        run_out.glob("turn-*.json"),
        key=lambda p: int(m.group(1)) if (m := re.search(r"turn-(\d+)", p.name)) else 0,
    )
    all_events, raw_parse_errors = [], 0
    for tf in turn_files:
        evs, errs = load_ndjson_or_json(tf)
        all_events.extend(evs)
        raw_parse_errors += errs
    event_source = "turn-json" if all_events else None

    if not all_events:
        sess_dir = run_out / "sessions"
        sess_files = sorted(sess_dir.rglob("*.jsonl")) if sess_dir.exists() else []
        for sf in sess_files:
            evs, errs = load_ndjson_or_json(sf)
            all_events.extend(evs)
            raw_parse_errors += errs
        if all_events:
            event_source = "session-jsonl"

    if not all_events:
        return {
            "event_source": None, "raw_ndjson_parse_errors": raw_parse_errors,
            "tool_call_counts": None, "tool_call_count_source": None, "test_run_tool_calls": None,
            "reproduced_before_first_edit": None, "harness_parse_errors": None, "total_tool_errors": None,
            "prompt_tokens_sum": None, "completion_tokens_sum": None, "reasoning_tokens_sum": None,
            "cache_read_tokens_sum": None, "cache_write_tokens_sum": None, "assistant_turns": None,
        }

    counts_toolcall, ordered_toolcall = {}, []
    counts_start, ordered_start = {}, []
    usage_list = []
    results_by_id = {}
    error_events = []
    harness_parse_error_count = 0
    idx = 0

    for e in all_events:
        for node in walk_dicts(e):
            if node.get("type") == "toolCall" and isinstance(node.get("name"), str):
                name = node["name"]
                counts_toolcall[name] = counts_toolcall.get(name, 0) + 1
                args = node.get("arguments")
                argtext = ""
                if isinstance(args, dict):
                    argtext = " ".join(str(v) for v in args.values() if isinstance(v, (str, int, float)))
                ordered_toolcall.append({"name": name, "idx": idx, "args_text": argtext, "id": node.get("id")})
                idx += 1
            elif node.get("type") == "custom" and node.get("customType") == "tool_execution_start":
                data = node.get("data") or {}
                tn = data.get("toolName")
                if tn:
                    counts_start[tn] = counts_start.get(tn, 0) + 1
                    a = data.get("args") if isinstance(data.get("args"), dict) else {}
                    argtext = " ".join(str(v) for v in a.values())
                    ordered_start.append(
                        {"name": tn, "idx": idx, "args_text": argtext, "id": data.get("toolCallId")}
                    )
                    idx += 1
            elif node.get("type") == "message" and isinstance(node.get("message"), dict):
                m = node["message"]
                if m.get("role") == "assistant" and isinstance(m.get("usage"), dict):
                    usage_list.append(m["usage"])
                elif m.get("role") == "toolResult":
                    content = m.get("content")
                    text = ""
                    if isinstance(content, list):
                        text = " ".join(c.get("text", "") for c in content if isinstance(c, dict))
                    elif isinstance(content, str):
                        text = content
                    res = {"toolName": m.get("toolName"), "text": text, "isError": bool(m.get("isError")),
                           "details": m.get("details")}
                    tcid = m.get("toolCallId")
                    if tcid:
                        results_by_id[tcid] = res
                    if res["isError"]:
                        error_events.append({"toolName": res["toolName"], "text": text[:300]})
                        if HARNESS_ERR_RE.search(text):
                            harness_parse_error_count += 1

    if sum(counts_toolcall.values()) > 0:
        tool_call_counts, tool_calls_ordered, tc_source = counts_toolcall, ordered_toolcall, "toolCall-blocks"
    else:
        tool_call_counts, tool_calls_ordered, tc_source = counts_start, ordered_start, "tool_execution_start"

    test_run_calls = []
    for tc in tool_calls_ordered:
        if tc["name"].lower() in RUN_TOOL_NAMES:
            at = tc["args_text"] or ""
            if (test_cmd and test_cmd in at) or re.search(r"(?i)vitest|pytest|npm (run )?(test|unit)|node --test", at):
                test_run_calls.append(tc)

    first_edit_idx = None
    for tc in tool_calls_ordered:
        if tc["name"].lower() in ("edit", "write"):
            first_edit_idx = tc["idx"]
            break

    first_failing_run_idx = None
    for tc in tool_calls_ordered:
        if tc["name"].lower() in RUN_TOOL_NAMES and is_failure_result(results_by_id.get(tc["id"])):
            first_failing_run_idx = tc["idx"]
            break

    if first_edit_idx is None:
        reproduced_before_edit = None
    elif first_failing_run_idx is None:
        reproduced_before_edit = False
    else:
        reproduced_before_edit = first_failing_run_idx < first_edit_idx

    def usum(key):
        vals = [u.get(key) for u in usage_list if isinstance(u.get(key), (int, float))]
        return sum(vals) if vals else (0 if usage_list else None)

    reasoning_vals = []
    for u in usage_list:
        for k in ("reasoning", "reasoningTokens", "thinkingTokens", "thinking"):
            v = u.get(k)
            if isinstance(v, (int, float)):
                reasoning_vals.append(v)
                break
    reasoning_sum = sum(reasoning_vals) if reasoning_vals else None

    return {
        "event_source": event_source,
        "raw_ndjson_parse_errors": raw_parse_errors,
        "tool_call_counts": tool_call_counts,
        "tool_call_count_source": tc_source,
        "test_run_tool_calls": len(test_run_calls),
        "reproduced_before_first_edit": reproduced_before_edit,
        "harness_parse_errors": harness_parse_error_count,
        "total_tool_errors": len(error_events),
        "prompt_tokens_sum": usum("input"),
        "completion_tokens_sum": usum("output"),
        "reasoning_tokens_sum": reasoning_sum,
        "cache_read_tokens_sum": usum("cacheRead"),
        "cache_write_tokens_sum": usum("cacheWrite"),
        "assistant_turns": len(usage_list) if usage_list else None,
    }


def wallclock_from_driver_log(run_out: Path):
    f = run_out / "driver.log"
    if not f.exists():
        return None
    times = re.findall(r"^\[(\d\d):(\d\d):(\d\d)\]", f.read_text(encoding="utf-8", errors="replace"), re.M)
    if len(times) < 2:
        return None
    def to_sec(t):
        return int(t[0]) * 3600 + int(t[1]) * 60 + int(t[2])
    secs = [to_sec(t) for t in times]
    delta = secs[-1] - secs[0]
    if delta < 0:
        delta += 24 * 3600  # best-effort midnight rollover; driver.log has no date component
    return delta


# --------------------------------------------------------------------------------------
# orchestration
# --------------------------------------------------------------------------------------

def score_task(task: str, label: str, p1_timeout=300, p2_timeout=900, p3_timeout=300) -> dict:
    turns = load_turns(task)
    base_repo = base_repo_dir(turns)
    wt = worktree_dir(task, label)
    run_out = run_out_dir(task, label)
    run_out.mkdir(parents=True, exist_ok=True)

    result = {"task": task, "label": label, "worktree": str(wt), "run_dir": str(run_out)}
    warnings = []
    if not wt.exists():
        warnings.append(f"worktree not found: {wt}")
    if not (run_out / "final.diff").exists():
        warnings.append("final.diff missing in run dir")
    if warnings:
        result["warnings"] = warnings

    if wt.exists():
        p1 = run_p1(task, wt, base_repo, run_out, p1_timeout)
        p2 = run_p2(wt, turns, p2_timeout)
        p3 = run_p3(task, wt, base_repo, run_out, label, p3_timeout)
    else:
        p1 = p2 = p3 = {"status": "ERROR", "reason": "no worktree"}

    secondary = secondary_metrics(task, run_out)
    events = analyze_events(run_out, turns.get("test_cmd", ""))
    wallclock = wallclock_from_driver_log(run_out)

    overall_pass = all(x.get("status") == "PASS" for x in (p1, p2, p3))
    result.update({
        "overall_pass": overall_pass,
        "P1": p1, "P2": p2, "P3": p3,
        "secondary": secondary,
        "events": events,
        "wallclock_seconds": wallclock,
    })
    (run_out / "score.json").write_text(json.dumps(result, indent=2, default=str), encoding="utf-8")
    return result


def one_line_summary(r: dict) -> str:
    ov = "PASS" if r["overall_pass"] else "FAIL"
    sec = r["secondary"]
    ev = r["events"]
    tool_total = sum(ev["tool_call_counts"].values()) if ev.get("tool_call_counts") else None
    return (
        f"{r['task']}/{r['label']}: {ov}  (P1={r['P1']['status']} P2={r['P2']['status']} P3={r['P3']['status']})  "
        f"loc +{sec['loc_added']}/-{sec['loc_removed']} files={sec['files_touched_count']} "
        f"tools={tool_total} wall={r['wallclock_seconds']}s"
    )


def write_scoreboard(results: list[dict]):
    tasks_present = [t for t in TASKS if any(r["task"] == t for r in results)]
    labels_present = sorted(set(r["label"] for r in results))
    index = {(r["task"], r["label"]): r for r in results}

    lines = ["# Scoreboard", "", "| task | " + " | ".join(labels_present) + " |",
              "|---|" + "---|" * len(labels_present)]
    for t in tasks_present:
        row = [t]
        for l in labels_present:
            r = index.get((t, l))
            if not r:
                row.append("")
                continue
            ov = "PASS" if r["overall_pass"] else "FAIL"
            sec = r["secondary"]
            ev = r["events"]
            tool_total = sum(ev["tool_call_counts"].values()) if ev.get("tool_call_counts") else "n/a"
            cell = (
                f"**{ov}**<br>P1={r['P1']['status']} P2={r['P2']['status']} P3={r['P3']['status']}<br>"
                f"<sub>loc +{sec['loc_added']}/-{sec['loc_removed']}, files={sec['files_touched_count']}, "
                f"tools={tool_total}, test-runs={ev.get('test_run_tool_calls')}, "
                f"repro-first={ev.get('reproduced_before_first_edit')}, wall={r['wallclock_seconds']}s</sub>"
            )
            row.append(cell)
        lines.append("| " + " | ".join(row) + " |")
    RUNS.mkdir(parents=True, exist_ok=True)
    (RUNS / "scoreboard.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("task", nargs="?", choices=TASKS)
    ap.add_argument("label", nargs="?")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--p1-timeout", type=int, default=300)
    ap.add_argument("--p2-timeout", type=int, default=900)
    ap.add_argument("--p3-timeout", type=int, default=300)
    args = ap.parse_args()

    if args.all:
        results = []
        for task in TASKS:
            d = RUNS / task
            if not d.exists():
                continue
            for label_dir in sorted(p for p in d.iterdir() if p.is_dir()):
                if not (label_dir / "final.diff").exists():
                    continue
                r = score_task(task, label_dir.name, args.p1_timeout, args.p2_timeout, args.p3_timeout)
                print(one_line_summary(r))
                results.append(r)
        if results:
            write_scoreboard(results)
            print(f"wrote {RUNS / 'scoreboard.md'}")
        else:
            print("no run dirs with final.diff found under " + str(RUNS))
        return

    if not args.task or not args.label:
        ap.error("task and label are required unless --all")
    r = score_task(args.task, args.label, args.p1_timeout, args.p2_timeout, args.p3_timeout)
    print(one_line_summary(r))


if __name__ == "__main__":
    main()
